### ISSUE TITLE
Slider laggy with react-native-navigation

### ISSUE THREAD

**Issue by solonifer** [ptomasroos/react-native-multi-slider#65] opened 2018-03-27 23:01 UTC
- [x] I have searched [existing issues](https://github.com/ptomasroos/react-native-multi-slider/issues)
- [x] I am using the [latest multi slider version](https://www.npmjs.com/package/@ptomasroos/react-native-multi-slider)

If I use this component alone - it works perfect.
But if I use it with [react-native-navigation](https://github.com/wix/react-native-navigation) with drawer enabled, once I swipe [react-native-multi-slider](react-native-multi-slider) - it slides a bit and stuck and then drawer is opening.

Default [React Native Slider](https://facebook.github.io/react-native/docs/slider.html) works perfect with [react-native-navigation](https://github.com/wix/react-native-navigation) + drawer without lagging.

## Steps to Reproduce
[react-native-navigation](https://github.com/wix/react-native-navigation) with drawer enabled + [react-native-multi-slider](https://github.com/ptomasroos/react-native-multi-slider)
## Expected Behavior
Slider should continue to slide.

## Actual Behavior
Slider slides a bit then stack and drawer opens.

**Comment by ptomasroos** [comment] 2018-03-28 07:20
Since you didnt provide a repository I will close this, if you provide one I will happily help you out fixing this.

**Closed by ptomasroos** 2018-03-28 07:20 UTC

**Comment by solonifer** [comment] 2018-04-01 05:25
@ptomasroos thank you for reply.

I would like to give you another example, simple to reproduce:
```
import MultiSlider  from '@ptomasroos/react-native-multi-slider';

<ScrollView>
  <MultiSlider />
</ScrollView>
```

What happen is when you touch slider and start sliding and without releasing a finger pulling down - ScrollView scrolls down. What I think should happen is that MultiSlider should cancel ScrollView scrolling until you finish your gesture on MultiSlider.

Hope I was clear enough :)

**Comment by ptomasroos** [comment] 2018-04-01 06:58
I've added a section to the README https://github.com/ptomasroos/react-native-multi-slider

**Comment by ptomasroos** [comment] 2018-08-09 10:30
@qubitron we use this only within scrollview's are you sure you've implemented the disabling of scrolling in the ScrollView correctly? Or can you post a expo.io example for me to see this in order to help you out. Without a reproducible example its impossible to imagine for me.

**Comment by qubitron** [comment] 2018-08-10 06:39
I figured out the problem, it was because I was hosting the MultiSlider inside of a stateless component that was being defined inside of the render function. The stateless component was being re-defined on every render call, which was causing the MultiSlider to stop panning on each render. Sorry for the false alarm!

**Comment by uday8373** [comment] 2021-01-06 09:56
HI, I am facing the same issue with react-native-navigation when i am not using the drawer it is okay but inside drawer component the slider is not moving it is sticking.
